
project_id = "msujdvczbmnhkfpjikwb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54327
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://msujdvczbmnhkfpjikwb.supabase.co"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[[auth.providers.email]]
enabled = true

[functions.ingest_residents]
verify_jwt = false
